In [1]:
import numpy as np
from city_planner_gym import CityPlanningEnv

In [4]:
# Initialize the environment
env = CityPlanningEnv()

# Reset the environment to get the initial state
obs = env.reset()
print("Initial Observation:")
print("Grid:\n", obs['grid'])
print("Budget:", obs['budget'])
print()

# Run a loop to perform random actions until the environment is done
done = False
step_count = 0
total_reward = 0
while not done:
    # Randomly select a row, column, and building type
    row = np.random.randint(0, 10)
    col = np.random.randint(0, 10)
    building_type = np.random.randint(0, 6)
    action = (row, col, building_type)

    # Take a step in the environment
    obs, reward, done, info = env.step(action)

    # Print the action and result
    print(f"Step {step_count}: Placing building type {building_type} at ({row}, {col})")
    print("Reward:", reward)
    print("Remaining Budget:", obs['budget'])
    print("Current Grid:\n", obs['grid'])
    print()

    # Increment step count
    step_count += 1
    total_reward += reward

print(f"Simulation finished. Total Reward: {total_reward}")
env.close()

Initial Observation:
Grid:
 [[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Budget: 1000

Step 0: Placing building type 0 at (0, 4)
Reward: 50
Remaining Budget: 900
Current Grid:
 [[0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

Step 1: Placing building type 3 at (1, 4)
Reward: 100
Remaining Budget: 890
Current Grid:
 [[0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

Step 2: Placing building type 5 at (8, 9)
Reward: 25
Remaining Budget: 885
Current

In [5]:
# Get average reward from playing randomly

env = CityPlanningEnv()

# Reset the environment to get the initial state

num_episodes = 5000
rewards = []
for i in range(num_episodes):
    done = False
    step_count = 0
    total_reward = 0
    obs = env.reset()
    while not done:
        # Randomly select a row, column, and building type
        row = np.random.randint(0, 10)
        col = np.random.randint(0, 10)
        building_type = np.random.randint(0, 6)
        action = (row, col, building_type)

        # Take a step in the environment
        obs, reward, done, info = env.step(action)

        # Increment step count
        step_count += 1
        total_reward += reward
    rewards.append(total_reward)

print(f'Average reward ({num_episodes} episodes): {sum(rewards) / len(rewards)}')

Average reward (5000 episodes): 599.585
